[build]
  # This is a static HTML site - no build command needed
  command = "echo 'Static site - no build required'"
  publish = "."

# Optional: Configure redirects for single page routing if needed
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404